### ISSUE TITLE
does EasyX open source?

### ISSUE THREAD

**Issue by labspc** [zouhuidong/EasyWin32#1]
[EasyX  https://easyx.cn/ ](https://easyx.cn/)  自身是不是闭源的图形库，我看有`EasyXw.lib` 库文件

**Comment by zouhuidong** [comment]
EasyX 不开源。有 EasyXw.lib 库文件并不说明开源吧？

**Comment by zouhuidong** [comment]
顺便一说，EasyWin32 已经更新为 HiEasyX 了，你怎么还在这里留言（哭笑）。
